### ISSUE TITLE
@import gets removed from style tag

### ISSUE THREAD

**Issue by andrispraulitis** [jjriv/emogrifier#331] opened 2016-08-26 14:26 UTC
I'm trying to import custom google fonts css file but emogrifier removes them. How can I use @import?

**Comment by oliverklee** [comment] 2016-09-07 10:19
This currently is not support, and I'm also not sure that we should support it. I've explained this in #334 .

(Closing as a duplicate of #334 .)

**Closed by oliverklee** 2016-09-07 10:19 UTC
