### ISSUE TITLE
Emogrifyer and meta-specified charset=utf-8 problem

### ISSUE THREAD

**Issue by clindh** [jjriv/emogrifier#182] opened 2015-06-24 13:36 UTC
I have a problem with Emogrifyer when the parsed html contains a meta-specified charset e.g.
&lt; meta http-equiv="Content-Type" content="text/html; charset=utf-8” &gt;

The UTF-8 characters are somehow mangled, but ONLY when charset=utf-8 is present

I have prepared a test in this sandbox where you can replicate the problem
http://sandbox.onlinephpfunctions.com/code/fc85874bb3c6f0a44406fa446885e184c6bb901b

This code tries to replicate what Emogrifier does internally.
You can try with and without the "charset=utf-8" on Content-Type by uncommenting the str_replace line

Now check this version out
http://sandbox.onlinephpfunctions.com/code/cc431cc871c63202673aff717a912c855966cf13

Here the two mb_converts are done after saving back to HTML from DOMDocument.
Note the reveresed effect, UTF8 is mangled if charset=utf-8 is NOT present. So the DOMDocument parser does something strange to the charset.

Do you have any clue what is going on? 

If you do not see a fix, can we have the preserveEncoding feature back so Emogrifyer can be told not do this final mb_convert, that messesup the output?

**Comment by oliverklee** [comment] 2015-06-24 16:11
Hi @clindh, thanks for the bug report. Could you please try whether PR #175 fixes the problem for you?

**Comment by andrejdanko** [comment] 2015-06-30 22:16
I fixed is by removing mb_convert_encoding (as the DOMDocument is already UTF-8) and then it works well.

**Comment by oliverklee** [comment] 2015-07-05 22:22
HI @clindh, I've just merged #189. Could you please test whether the problem is solved for you using the current master?

**Comment by oliverklee** [comment] 2015-07-11 10:26
Closing due to no feedback. @clindh Please feel free to reopen this ticket if the problem still occurs.

**Closed** 2015-07-11 10:26 UTC
Labels: bug, waiting for feedback
