### ISSUE TITLE
[ and ] in img src attributes are encoded to %5B and %5D (Drupal-specific)

### ISSUE THREAD

**Issue by monstrfolk** [jjriv/emogrifier#369] opened 2017-02-15 00:43 UTC
I did not do anything special to create this output. Just used Emogrifier per instructions.

You can see the same behavior at [https://www.myintervals.com/emogrifier.php](url)

CSS
```
div#container { margin: 1em auto; }
img { padding:10px; }
```

HTML
```
<html lang="en">
<body>
    <div id="container">
        <img src="[source-inside-brackets]">
    </div>
</body>
</html>
```

ACTUAL
```
<html lang="en"><body>
    <div id="container" style="margin: 1em auto;">
        <img src="%5Bsource-inside-brackets%5D" style="padding:10px;">
</div>
</body></html>
```

EXPECTED
```
<html lang="en"><body>
    <div id="container" style="margin: 1em auto;">
        <img src="[source-inside-brackets]" style="padding:10px;">
</div>
</body></html>
```

**Comment by oliverklee** [comment] 2017-02-15 11:14
@monstrfolk Could you please the code that is needed to reproduce the problem, the expected results and the actual results?

And could you please check that this actually breaks the images? IIRC, encoding the [ and ] in URLs in HTML documents is valid.

**Comment by monstrfolk** [comment] 2017-02-16 06:16
Sorry to the very bad bug submission. I was traveling, trying to submit the report on my phone, and then lost internet. I have explained in more detail.

**Comment by oliverklee** [comment] 2017-02-16 07:59
@monstrfolk Thanks for the explanation!

Have you tested that this actually is a problem, or do the images still load fine?

**Comment by monstrfolk** [comment] 2017-02-16 08:00
It is a problem on certain platforms. Images do not load.

**Comment by oliverklee** [comment] 2017-02-16 08:06
Can you specify on which platforms the problem occurs?

**Comment by monstrfolk** [comment] 2017-02-16 08:08
Drupal

**Comment by oliverklee** [comment] 2017-02-16 08:09
Could you please post details? E.g., does Drupal mangle the encoded brackets, is it a problem in certain email clients etc.

**Comment by monstrfolk** [comment] 2017-02-16 08:11
It is a problem when Drupal tries to convert tokens. It does not recognize %5B and %5D. The tokens do not get converted.

**Comment by oliverklee** [comment] 2017-02-16 08:13
Ah, so the problem ist that the input HTML actually is not valid, but should be valid after Drupal has processed it (if I understand it correctly). However, the behavior of Emogrifier is only well-defined for valid HTML input.

Is there a possibility that you use different delimiters for the tokens, e.g. curly braces (which will not get encoded IIRC)?

**Comment by monstrfolk** [comment] 2017-02-16 08:16
No. All tokens are defined by [ and ]. I have committed a patch to the Emogrifier plugin for Drupal that replaces all the %5B and %5D back to [ and ] after Emogrifier processes HTML. It would be nice to remove that step form the module

**Comment by oliverklee** [comment] 2017-02-16 09:41
Ah, thanks for the information. Would you be willing to create a pull request for this for Emogrifier?

**Comment by monstrfolk** [comment] 2017-02-16 15:06
I committed the patch for the Drupal project. [https://www.drupal.org/project/emogrifier](url). I don't think the pull request would really help.

This is what I did.
```
$text = @$emogrifier->emogrify();
$text = str_replace('%5B', '[', $text);
$text = str_replace('%5D', ']', $text);
```

**Comment by oliverklee** [comment] 2017-02-16 18:12
Actually, a PR would help as this is the way to get code changes into Emogrifier. :-)

(Usually, the people to whom an issue is important create a PR. And if none of them creates it, there will be no fix for this issue.)

**Comment by apih** [comment] 2017-02-17 13:25
From my experience, the value of `href` and `src` attributes will be encoded by DOMDocument when the DOM is dumped into string using `saveHTML` method. Since Emogrifier uses DOMDocument underneath, I don't think this is avoidable, unless someone wants to write code to decode back all `href` and `src` attributes in the final HTML string.

**Comment by oliverklee** [comment] 2017-02-17 13:31
Exactly. Thanks for the explanation.

That's why I would prefer Drupal to use different delimiters that won't get auto-encoded (e.g., curly braces).

**Comment by apih** [comment] 2017-02-17 15:17
Curly braces are encoded as well. That was my experience, haha. Since I knew my templates used curly braces, I employed the same solution as @monstrfolk in my code, which was to replace all encoded curly braces in the final HTML string.

**Comment by monstrfolk** [comment] 2017-02-17 15:20
This issue sounds like a can't fix because of DomDocument. Does anyone know if DomDocument can be configured to selectively encode or exclude specific characters. That would be the best solution IMO.

**Comment by oliverklee** [comment] 2017-02-17 15:22
Concerning the workflow, I think it would make sense to first replace the markers and then run Emogrifier on the result instead of the other way around (i.e., a change to Drupal). This would remove the need for hackish workarounds. What do you think?

**Comment by apih** [comment] 2017-02-17 15:28
Yes, that's right. Emogrifier should be run last, before sending the HTML out as an email.

**Comment by oliverklee** [comment] 2017-02-17 15:30
@monstrfolk Would https://github.com/bjaxelsen/emogrifier be the correct project to report an issue for this?

**Comment by monstrfolk** [comment] 2017-02-17 15:32
Unfortunately, a change like that for Drupal will not be possible. Using [ and ] for variable replacement is built into the core.

**Comment by oliverklee** [comment] 2017-02-17 15:32
With my question about creating a ticket, I was thinking of changing the order or how things are done, not about changing the [ and ].

**Comment by monstrfolk** [comment] 2017-02-17 15:34
I don't think this issue can be reported anywhere currently. Both Emogrifier and Drupal are working as designed. It would be nice to selectively exclude specific characters being encoded. This feature would be useful for { and } as well as @apih explained the same issue.

**Comment by oliverklee** [comment] 2017-02-17 15:40
@monstrfolk So it won't be possible to change the Emogrifier Drupal integration that the HTML is emogrified _after_ the markers have been replaced?

**Comment by monstrfolk** [comment] 2017-02-17 16:08
Tokens (variables) are replaced after input filters, which is how the Emogifier module works. I will look into that also. Thanks.

**Comment by oliverklee** [comment] 2017-02-17 16:09
All right, thanks!

Closing this ticket at this isn't an issue in Emogrifier.

**Closed by oliverklee** 2017-02-17 16:09 UTC
